
project_id = "pnfklluwvlcgjaqlbcxu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[functions]
timeout_seconds = 60
