// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnfklluwvlcgjaqlbcxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuZmtsbHV3dmxjZ2phcWxiY3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNTMyNzgsImV4cCI6MjA1NDgyOTI3OH0.7LavPsvD2s-Rm-fLD-ZboUDTfdy4ChMjdQrGgCg3iVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);